name = "snoopybank"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "snoopy-db"
database_id = "a86a632e-6116-48e1-9263-061b2b89984c"


